---
title: XXL Freshmen Archive
description: Every freestyle and cypher from the annual XXL Freshmen List issue
meta_img:
twitter:
favicon: /images/xxl-favicon.ico 
url:
gtm:
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  years:
    output: false
defaults:
- scope:
    path: ''
  values:
    layout: default
